"""Build the deterministic normalized Moon authoring asset."""

import argparse
from array import array
import math
import pathlib
import shutil
import sys

import bpy


SCRIPT_DIR = pathlib.Path(__file__).resolve().parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

from common import (  # noqa: E402
    build_manifest,
    canonicalize_ellipsoid_normals,
    create_pbr_material,
    create_uv_sphere,
    export_glb,
    print_manifest,
    reset_scene,
)
from moon_config import MODELS_ROOT, moon_config, normalized_relief_radius  # noqa: E402


SEGMENTS = 128
RINGS = 64
EXPECTED_TRIANGLES = 16_128


def arguments_after_separator(argv):
    return argv[argv.index("--") + 1 :] if "--" in argv else []


def parse_arguments(arguments):
    parser = argparse.ArgumentParser()
    parser.add_argument("--output-root", type=pathlib.Path, default=MODELS_ROOT)
    return parser.parse_args(arguments)


def _texture_by_role(config, role):
    return next(texture for texture in config.textures if texture.role == role)


def _height_samples(path, vertices):
    image = bpy.data.images.load(str(path.resolve()), check_existing=True)
    width, height = (int(value) for value in image.size)
    if (width, height) != (2048, 1024):
        raise ValueError(f"Moon height map must be 2048x1024; measured {width}x{height}")
    channels = int(image.channels)
    pixels = array("f", [0.0]) * (width * height * channels)
    image.pixels.foreach_get(pixels)
    samples = []
    for vertex in vertices:
        direction = vertex.co.normalized()
        u = (0.5 + math.atan2(-direction.y, direction.x) / (2.0 * math.pi)) % 1.0
        v = 0.5 + math.asin(max(-1.0, min(1.0, direction.z))) / math.pi
        x = min(width - 1, int(u * width))
        y = min(height - 1, max(0, round(v * (height - 1))))
        samples.append(float(pixels[(y * width + x) * channels]))
    maximum = max(samples)
    minimum = min(samples)
    if maximum - minimum <= 1e-6:
        raise ValueError("Moon height map has no usable relief range")
    return tuple((sample - minimum) / (maximum - minimum) for sample in samples)


def _center_and_normalize(obj):
    minimum = [min(vertex.co[axis] for vertex in obj.data.vertices) for axis in range(3)]
    maximum = [max(vertex.co[axis] for vertex in obj.data.vertices) for axis in range(3)]
    center = [(low + high) * 0.5 for low, high in zip(minimum, maximum)]
    for vertex in obj.data.vertices:
        for axis in range(3):
            vertex.co[axis] -= center[axis]
    radius = max(vertex.co.length for vertex in obj.data.vertices)
    for vertex in obj.data.vertices:
        vertex.co /= radius
    return tuple(center), radius


def _displace(surface, height_path, mean_radius_km, relief_range_km):
    samples = _height_samples(height_path, surface.data.vertices)
    for vertex, sample in zip(surface.data.vertices, samples):
        direction = vertex.co.normalized()
        vertex.co = direction * normalized_relief_radius(
            sample, mean_radius_km, relief_range_km
        )
    return _center_and_normalize(surface)


def _publish_files(config, output_dir):
    output_paths = []
    for texture in config.textures:
        if texture.role == "height":
            continue
        destination = output_dir / texture.output_name
        if texture.source_path.resolve() != destination.resolve():
            shutil.copyfile(texture.source_path, destination)
        output_paths.append(destination)

    source_record = _texture_by_role(config, "height").source_path.parent / "SOURCES.md"
    upstream = source_record.read_text(encoding="utf-8").split(
        "## Derived Moon maps", 1
    )[0].rstrip() + "\n"
    sources = (
        "# Sources — Moon\n\n"
        "- `moon.glb` — `tools/blender/build_moon.py` — Solar Voyager original asset; all rights reserved for project distribution — deterministic 128×64 normalized sphere displaced from the LOLA height field.\n"
        "- `moon_albedo.jpg` — NASA SVS LROC color (https://svs.gsfc.nasa.gov/4720) — NASA/US Government work — resized to 4096×2048, contrast-enhanced by 1.08, and JPEG-encoded at quality 88.\n"
        "- `moon_normal.png` — NASA SVS LOLA elevation (https://svs.gsfc.nasa.gov/4720) — NASA/US Government work — macro normal generated by `tools/textures/prepareMoonMaps.mjs` from the filtered 2048×1024 height field.\n"
        "- `moon_detail_albedo.jpg` — `tools/textures/prepareMoonMaps.mjs`, seed 301 — Solar Voyager original asset; all rights reserved for project distribution — periodic isotropic regolith/microcrater field repeated to 1024×1024 and JPEG-encoded.\n"
        "- `moon_detail_normal.png` — `tools/textures/prepareMoonMaps.mjs`, seed 301 — Solar Voyager original asset; all rights reserved for project distribution — tangent-space normal from the periodic field, repeated to 1024×1024 and PNG-encoded.\n\n"
        "## Upstream records\n\n"
        + upstream
    )
    (output_dir / "SOURCES.md").write_text(sources, encoding="utf-8", newline="\n")
    return tuple(output_paths)


def build(output_root):
    config = moon_config()
    output_dir = pathlib.Path(output_root).resolve() / config.category / config.body_id
    output_dir.mkdir(parents=True, exist_ok=True)

    reset_scene()
    surface = create_uv_sphere(config.body_id, segments=SEGMENTS, rings=RINGS, radius=1.0)
    center_offset, pre_normalization_radius = _displace(
        surface,
        _texture_by_role(config, "height").source_path,
        config.mean_radius_km,
        config.relief_range_km,
    )
    material = create_pbr_material(
        "mat_surface",
        roughness=0.9,
        albedo_path=_texture_by_role(config, "albedo").source_path,
        normal_path=_texture_by_role(config, "normal").source_path,
    )
    surface.data.materials.append(material)

    glb_path = export_glb((surface,), output_dir / "moon.glb", active=surface)
    canonicalize_ellipsoid_normals(glb_path, 1.0)
    textures = _publish_files(config, output_dir)
    manifest = build_manifest(config.body_id, config.category, (surface,), glb_path, textures)
    manifest["reliefRangeKm"] = config.relief_range_km
    manifest["preNormalizationRadius"] = round(pre_normalization_radius, 9)
    manifest["centerOffset"] = [round(component, 9) for component in center_offset]
    print_manifest(manifest)

    if manifest["triangles"] != EXPECTED_TRIANGLES:
        raise RuntimeError(
            f'Moon emitted {manifest["triangles"]} triangles, expected {EXPECTED_TRIANGLES}'
        )
    if abs(manifest["radius"] - 1.0) > 1e-6:
        raise RuntimeError(f'Moon radius is {manifest["radius"]}, expected 1.0')
    return manifest


def main(argv=None):
    arguments = parse_arguments(arguments_after_separator(sys.argv) if argv is None else argv)
    build(arguments.output_root)


if __name__ == "__main__":
    try:
        main()
    except (OSError, RuntimeError, ValueError) as error:
        print(f"Moon build failed: {error}", file=sys.stderr, flush=True)
        raise SystemExit(2) from error
