"""Build the disposable headless acceptance sphere for T0030."""

import argparse
import math
import pathlib
import sys

import bpy


SCRIPT_DIR = pathlib.Path(__file__).resolve().parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

from common import (  # noqa: E402
    asset_category,
    body_by_id,
    build_manifest,
    create_pbr_material,
    create_quad_sphere,
    create_uv_sphere,
    export_glb,
    print_manifest,
    reset_scene,
)


def arguments_after_separator(argv):
    return argv[argv.index("--") + 1 :] if "--" in argv else []


def parse_arguments(argv):
    parser = argparse.ArgumentParser()
    parser.add_argument("--output-root", required=True, type=pathlib.Path)
    return parser.parse_args(arguments_after_separator(argv))


def validate_quad_sphere_uv(obj):
    uv_layer = obj.data.uv_layers.active
    if uv_layer is None:
        raise RuntimeError("Quad sphere has no UV layer")
    for polygon in obj.data.polygons:
        polygon_u = []
        for loop_index in polygon.loop_indices:
            position = obj.data.vertices[obj.data.loops[loop_index].vertex_index].co.normalized()
            uv = uv_layer.data[loop_index].uv
            expected_v = 0.5 + math.asin(max(-1.0, min(1.0, position.y))) / math.pi
            if abs(uv.y - expected_v) > 1e-6:
                raise RuntimeError("Quad sphere V coordinate is not latitude mapped")
            if math.hypot(position.x, position.z) > 1e-9:
                expected_u = (0.5 + math.atan2(position.z, position.x) / (2.0 * math.pi)) % 1.0
                wrapped_error = min(abs(uv.x - expected_u), abs(uv.x - expected_u - 1.0))
                if wrapped_error > 1e-6:
                    raise RuntimeError("Quad sphere U coordinate is not longitude mapped")
            polygon_u.append(uv.x)
        if max(polygon_u) - min(polygon_u) > 0.5 + 1e-6:
            raise RuntimeError("Quad sphere polygon crosses the equirectangular seam")


def main(argv=None):
    arguments = parse_arguments(sys.argv if argv is None else argv)
    body = body_by_id("sun")
    output_dir = arguments.output_root.resolve() / body["id"]
    output_dir.mkdir(parents=True, exist_ok=True)
    (output_dir / "SOURCES.md").write_text(
        "# Sources — sun\n\n"
        "- `sun.glb` — generated by `tools/blender/build_test_sphere.py` as the "
        "T0030 headless pipeline acceptance asset. No external textures.\n",
        encoding="utf-8",
    )

    reset_scene()
    quad_sphere = create_quad_sphere("quad-sphere-contract", subdivisions=3)
    validate_quad_sphere_uv(quad_sphere)
    bpy.data.objects.remove(quad_sphere, do_unlink=True)
    sphere = create_uv_sphere("sun", segments=128, rings=64)
    material = create_pbr_material(
        "mat_surface",
        base_color=(0.02, 0.01, 0.0, 1.0),
        roughness=1.0,
        emissive_color=(1.0, 0.83, 0.55, 1.0),
        emissive_strength=10.0,
    )
    sphere.data.materials.append(material)
    glb_path = export_glb((sphere,), output_dir / "sun.glb")
    manifest = build_manifest("sun", asset_category(body), (sphere,), glb_path)
    print_manifest(manifest)

    if manifest["triangles"] > 50_000:
        raise RuntimeError("Test sphere exceeds the 50,000 triangle Sun budget")
    if abs(manifest["radius"] - 1.0) > 1e-6:
        raise RuntimeError(f'Test sphere radius is {manifest["radius"]}, expected 1.0')


if __name__ == "__main__":
    main()
